apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/jhutar-tenant/devfile-sample/devfile-sample@sha256:4f15932c0a8ba9e4ca43dfdaa0ca53cd7dbc7e0050e47a46d2692dca6e0de0a9
        name: my-nodejs
        resources: {}
status: {}
